project:
  type: book
  output-dir: docs

book:
  title: "Introducción al Machine Learning aplicado a las Ciencias Sociales"
  author: "Christian Chiroque Ruiz"
  date: "09/18/2025"  #M/D/Y
  chapters:
    - index.qmd
    - part: Análisis exploratorio de datos para ML
      chapters: 
        - C1_intro.qmd
        - C2_EDA1.qmd
        - C3_EDA2.qmd

    - part: Métodos supervisados
      chapters: 
        - C4_RL.qmd
        - C5_RL2.qmd
        - C6_arboles.qmd
    
    - references.qmd

bibliography: references.bib

format:
  html:
    theme: 
      dark: darkly
      light: flatly
  pdf:
    documentclass: scrreprt
lang: es

editor: visual

